# Generated by Django 3.2.6 on 2021-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
